import React from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";

function buildPluginZip(project) {
  const zip = new JSZip();
  const root = `${project.name.replace(/\s+/g,'_') || 'my-plugin'}`;

  // basic plugin file
  const pluginHeader = `<?php
/*
Plugin Name: ${project.name}
Description: Plugin generated by WP Plugin Builder
Version: 1.0
Author: Generated
*/\n\n`;
  zip.file(`${root}/plugin.php`, pluginHeader + (project.files.find(f=>f.path==='plugin.php')?.content || ""));

  // add other files
  project.files.forEach(f => {
    if (f.path === 'plugin.php') return;
    zip.file(`${root}/${f.path}`, f.content || '');
  });

  return zip.generateAsync({type: "blob"});
}

export default function ExportTab({ project }) {
  async function handleExport() {
    try {
      const blob = await buildPluginZip(project);
      saveAs(blob, `${project.name || 'plugin'}.zip`);
    } catch (e) {
      console.error(e);
      alert('خطأ أثناء التصدير');
    }
  }

  return (
    <div>
      <p>تصدير البلجن كملف ZIP جاهز للتحميل والتثبيت على WordPress.</p>
      <div style={{display:'flex', gap:8, justifyContent:'flex-end'}}>
        <button onClick={handleExport} style={{padding:'8px 12px'}}>تنزيل ZIP</button>
      </div>
    </div>
  );
}
